// Turn the offset table into an ES module the browser can import. Prefers the traced
// table from the draught and falls back to the provisional one, printing loudly which
// it used so a provisional hull can never be mistaken for a traced one.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { ROOT } from './serve.js';

const traced = path.join(ROOT, 'docs/offsets.json');
const provisional = path.join(ROOT, 'docs/offsets.provisional.json');

let src = traced, grade = 'TRACED from ZAZ3067';
try { await fs.access(traced); } catch { src = provisional; grade = 'PROVISIONAL'; }

const data = JSON.parse(await fs.readFile(src, 'utf8'));
const body = `// GENERATED by tools/sync-offsets.js from ${path.relative(ROOT, src)}.
// Do not edit by hand — edit the source table or the extraction script and re-run
//   node tools/sync-offsets.js
//
// Grade: ${data.provenance?.grade ?? grade}
export const OFFSETS = ${JSON.stringify(data, null, 1)};
`;
await fs.writeFile(path.join(ROOT, 'src/spec/offsets.js'), body);
console.log(`offsets synced from ${path.relative(ROOT, src)} — ${data.provenance?.grade ?? grade}`);
if (src === provisional) console.log('  NOTE: the hull is not yet traced from the draught.');
